services:
  db:
    image: mariadb:10.7
    container_name: mariadb-container
    environment:
      MARIADB_ROOT_PASSWORD: rootpass
      MARIADB_DATABASE: testdb
      MARIADB_USER: testuser
      MARIADB_PASSWORD: testpass
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - '3306:3306'
  php:
    build: .
    depends_on:
      - db
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
      - ./php.ini:/usr/local/etc/php/php.ini
volumes:
  db-data:
